lane :OutputHelloWorld do
  puts "helloWorld"
end


lane :beta do
  build_app(export_method: "enterprise", output_directory: "~/Desktop/outputAPI")
  pgyer(api_key: "", user_key: "",password: "123456", update_description: "hellowrold")
end